name       : cgmanager
version    : 0.39
release    : 1
source     :
    - https://linuxcontainers.org/downloads/cgmanager/cgmanager-0.39.tar.gz : 9e65487fb4e4aa0a6acd87ba7f8f00b8007d8c52608aa6d411e72e6fe9445b7b
license    : LGPL-2.1
summary    : Another daemon for managing control groups
description: |
    Another daemon for managing control groups
builddeps  :
    - pkgconfig(libnih)
    - pkgconfig(libnih-dbus)
    - pkgconfig(dbus-1)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
