name       : cgmanager
version    : '0.41'
release    : 6
source     :
    - https://github.com/lxc/cgmanager/archive/v0.41.tar.gz : 7600bda5f1b80e6c09f4734fd288c0f3973aa5c80eec2ff3fe9e6c60628747e8
license    : LGPL-2.1-or-later
component  : system.utils
summary    : Another daemon for managing control groups
description: |
    Another daemon for managing control groups
builddeps  :
    - pkgconfig(libnih)
    - pkgconfig(libnih-dbus)
    - pkgconfig(dbus-1)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
